# This file lists the dependencies needed to build and test all of autotag_metadata.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: autotag_metadata
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=5,<6
  - click>=8,<9
  - pandas>=2,<3
  - pyqt>=5.15,<6
  - watchdog>=2.1,<2.2
  - dill>=0.3.4,<0.4
  - pyyaml>=6,<7
  - yamllint>=1.26,<2
  - pint>=0.18,<1
  - datapackage>=1.15,<2
  - pip>22
  - toml>0.10
  - desktop-app>0.2
