# This file lists the dependencies needed to build and test all of autotag_metadata.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: autotag_metadata
channels:
  - conda-forge
  - defaults
dependencies:
  - desktop-app
  - pip>=24
  - pyyaml
  - toml
  - watchdog
  - yamllint
  - pip:
    - PyQt6