name: Build GUI exe with Pyinstaller for Linux

on:
  workflow_call:

jobs:
  build:
    name: Build autotag-metadata Executable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        miniforge-variant: Mambaforge
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        mamba env update --quiet -n test -f environment-dev.yml
        mamba list
    - name: Pyinstaller
      shell: bash -l {0}
      run: |
        pyinstaller autotag-metadata.spec
    - name: Upload Artifact   
      uses: actions/upload-artifact@v3
      with:
        name: linux-exe
        path: dist/autotag-metadata
        if-no-files-found: error
