name: Documentation
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: Mambaforge }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment-dev.yml
          mamba list
      - name: build documentation
        shell: bash -l {0}
        run: |
          cd doc
          make html
          mv generated/html generated/html_
          mkdir generated/html
          mv generated/html_ generated/html/autotag-metadata
          touch generated/html/autotag-metadata/.nojekyll
      - name: fix permissions
        shell: bash -l {0}
        run: |
          # Strangely, the linkchecker modules are installed writable and linkchecker then refuses to load them.
          chmod -R a-w `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
      - name: detect broken links
        shell: bash -l {0}
        run: |
          python -m http.server 8880 --directory doc/generated/html &
          sleep 1
          # sphinx creates a genindex page with an edit on github button, but that page does not exist in the repository.
          linkchecker --check-extern http://localhost:8880/autotag-metadata --no-robots --ignore https://github.com/echemdb/autotag-metadata/blob/main/doc/genindex
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: doc/generated/html/autotag-metadata
          target-folder: docs
          single-commit: true
        if: ${{ github.event_name == 'push' }}

