name: Lint
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with: { submodules: recursive }
      - name: setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "${{ matrix.python }}"
          miniforge-variant: Mambaforge
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment-dev.yml
          mamba list
      - name: ruff lint
        shell: bash -l {0}
        run: |
          ruff check .
      - name: ruff format
        shell: bash -l {0}
        run: |
          ruff format .
      - name: ruff isort
        shell: bash -l {0}
        run: |
          ruff check --select I .