name: Build GUI exe with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.1.1
      with: { submodules: recursive }
    - uses: conda-incubator/setup-miniconda@v2
      with: { channels: "conda-forge", channel-priority: true }
    - name: install dependencies
      shell: bash -l {0}
      run: |
        mamba env update --quiet -n build -f environment.yml
        mamba list
    - name: install autotag-metadata
      shell: bash -l {0}
      run: |
        pip install --no-dependencies .

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: autotag-metadata
        path: dist/windows
